#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#include <stdio.h>
#include <string.h>

typedef enum {
    SUCCESS = 0,

    ERRO_NUMERO_SERIE = -1,
    TIPO_INVALIDO = -2,
    MODELO_INVALIDO = -3,
    PORTA_FECHADA = -4,
    CONEXAO_NEGADA = -5,
    CONEXAO_ATIVA = -6,

    BAUDRATE_INVALIDO = -11,
    DISPOSITIVO_NAO_EXISTE = -12,
    PERMISSAO_NEGADA = -13,
    ERRO_SERIAL_DESCONHECIDO = -14,
    DISPOSITIVO_JA_ESTA_ABERTO = -15,
    RECURSO_INDISPONIVEL = -16,
    OPERACAO_NAO_SUPORTADA = -17,
    SERIAL_TIMEOUT = -18,
    DISPOSITIVO_REMOVIDO_INESPERADAMENTE = -19,
    
    BAL_CONEXAO_ATIVA = -791,
    BAL_BALANCA_EM_USO = -792,
    BAL_BALANCA_INVALIDA = -793,
    BAL_NENHUMA_BALANCA_EM_USO = -794,
    
    BAL_PROTOCOLO_INVALIDO = -801,
    BAL_PROTOCOLO_EM_USO = -802,
    BAL_PROTOCOLO_NAO_SUPORTADO = -803,
    BAL_PROTOCOLO_NAO_SUPORTADO_PELAS_CONFIGS_SERIAIS = -804,
    BAL_NENHUM_PROTOCOLO_EM_USO = -805,
    
    BAL_BAUDRATE_NAO_SUPORTADO = -811,
    BAL_LENGTH_NAO_SUPORTADO = -812,
    BAL_PARITY_NAO_SUPORTADO = -813,
    BAL_STOPBITS_NAO_SUPORTADO = -814,
    BAL_BAUDRATE_INVALIDO = -815,
    BAL_LENGTH_INVALIDO = -816,
    BAL_PARITY_INVALIDO = -817,
    BAL_STOPBITS_INVALIDO = -818,
    BAL_COMBINACAO_DE_PARAMETROS_INVALIDA = -819,
    BAL_CONFIGS_SERIAIS_NAO_SUPORTADAS_PELO_PROTOCOLO = -820,
    
    BAL_QTD_LEITURAS_INVALIDA = -821,
    BAL_COMANDO_NAO_SUPORTADO_PELA_BALANCA = -822,
    BAL_COMANDO_NAO_SUPORTADO_PELO_PROTOCOLO = -823,
    BAL_PRECO_INVALIDO = -824,
    BAL_FALHA_NA_LEITURA_DO_PESO = -825,
    BAL_FALHA_AO_ENVIAR_PRECO = -826,
    CHAMADA_NAO_PERMITIDA = -827,

    ERRO_CARGA_DLL = -1234,
    ERRO_OBTENCAO_NUMERO_SERIE = -1235,
} E1ErrorCode;

typedef enum {
    SARA_EXCECAO_GENERICA = 4000200,
    SARA_ERRO_CARGA_DLL_FABRICANTE = 4010201,
    SARA_PERIFERICO_DESLIGADO = 4020200,
    SARA_ERRO_ABERTURA_OU_FECHAMENTO_PORTA = 4030200,
    SARA_TIMEOUT = 4090200,
    SARA_ERRO_OBTER_NUMERO_SERIE = 4130200,
} SaraErrorCode;

void mapE1ErrorCodesToSara(E1ErrorCode errorCode, char *saraError);

#endif