/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ccibm_ect_perifericos_BalancaPadraoSara */

#ifndef _Included_com_ccibm_ect_perifericos_BalancaPadraoSara
#define _Included_com_ccibm_ect_perifericos_BalancaPadraoSara
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ccibm_ect_perifericos_BalancaPadraoSara
 * Method:    obterNumeroSerie
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ccibm_ect_perifericos_BalancaPadraoSara_obterNumeroSerie
  (JNIEnv *, jobject);

/*
 * Class:     com_ccibm_ect_perifericos_BalancaPadraoSara
 * Method:    lerPeso
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ccibm_ect_perifericos_BalancaPadraoSara_lerPeso
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
